// DO NOT EDIT THIS FILE

#ifndef PACKER_H
#define PACKER_H

void packer_init(int balls_per_pack);

void packer_destroy(void);

// This function should block until there is
// another ball of the same colour available,
// and then return the id of that other ball.
// Ids can be any integer, and there are
// no guarantees on ordering or uniqueness.
// `other_balls` is a pointer to an array of length (n-1).
// You should write the ids of the other balls (in any order)
// into that array before returning.
void pack_ball(int colour, int id, int *other_ids);

#endif
