// DO NOT EDIT THIS FILE

#ifndef PACKER_H
#define PACKER_H

void packer_init(void);

void packer_destroy(void);

// This function should block until there is
// another ball of the same colour available,
// and then return the id of that other ball.
// Ids can be any integer, and there are
// no guarantees on ordering or uniqueness.
int pack_ball(int colour, int id);

#endif
